# Site settings
title: Jun's MARU
description: Modern-Blog A Elegant template for Jekyll
keywords: MARU, HANSOME, CAR
author: jun
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dearmysoul.github.io/jun/" # the base hostname & protocol for your site
